spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  output:
    ansi:
      enabled: "ALWAYS"
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:file:./db/java-shareit
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true

logging.level:
  ru.yandex.practicum.filmorate: TRACE
  org:
    zalando.logbook: TRACE
  springframework:
    orm:
      jpa: "INFO"
      jpa.JpaTransactionManager: "DEBUG"
    transaction: "INFO"
    transaction.interceptor: "TRACE"