server:
  port: 8090
spring:
  jpa:
    show-sql: true
    properties:
      hibernate.jdbc.time_zone: UTC
  output:
    ansi:
      enabled: "ALWAYS"
  sql:
    init:
      mode: always
  datasource:
    username: "postgres"
    password: "postgres"
    url: "jdbc:postgresql://localhost:5433/java-shareit"
    driver-class-name: "org.postgresql.Driver"

logging.level:
  ru.yandex.practicum.java-shareit: TRACE
  org:
    zalando.logbook: TRACE
  springframework:
    orm:
      jpa: "INFO"
      jpa.JpaTransactionManager: "DEBUG"
    transaction: "INFO"
    transaction.interceptor: "TRACE"